# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

name: "Generate Matrix"
description: "Creates a dynamic matrix for all build configurations that we have."
inputs:
  strategy: # "big-merge" or "pgo"
    description: 'build strategy'
    default: "all"
  lookback_days:
    description: "A list of integers for how many days to look back separated by space. \"0\" means just today."
    default: "0 1 2"
outputs:
  matrix:
    description: "The build matrix to use in consequential jobs"
    value: ${{ steps.set-matrix.outputs.myoutput }}
runs:
  using: "composite"
  steps:
    - name: Setup Copr config file
      shell: bash
      env:
        # You need to have those secrets in your repo.
        # See also: https://copr.fedorainfracloud.org/api/.
        COPR_CONFIG_FILE: ${{ secrets.COPR_CONFIG }}
      run: |
        mkdir -p ~/.config
        echo "$COPR_CONFIG_FILE" > ~/.config/copr
    - id: set-matrix
      shell: bash
      run: |
        echo "myoutput=$(python3 snapshot_manager/main.py --strategy ${{ inputs.strategy }} --lookback ${{ inputs.lookback_days }})" >> $GITHUB_OUTPUT
