# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

name: "Prepare Python"
description: "Sets up the python environment"
inputs:
  checkout-path:
    description: "Where this project was checked out"
    required: false
    default: "."
  use-system-python:
    description: "Set to true if you want to use the python installation from the OS"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - id: os-check
      shell: bash
      run: |
        if -e /etc/fedora-release; then
          fedora=true
        fi
        echo "is-fedora=$fedora" >> $GITHUB_OUTPUT
    - name: "Setup python"
      uses: actions/setup-python@v5
      if: "${{ inputs.use-system-python != 'true' }}"
      with:
        python-version: 3.12
        cache: 'pip'

    # libkrb5-dev is needed to build the koji module with pip
    - name: Install libkrb5-dev
      shell: bash
      run: |
        if [ "${{ steps.os-check.outputs.is-fedora }}" = "true" ]; then
          sudo dnf install -y krb5-devel
        else
          sudo apt-get update
          sudo apt-get install libkrb5-dev
        fi

    - name: "Install and upgrade pip"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: "Install python dependencies for project"
      shell: bash
      run: |
        pip install -r ${{ inputs.checkout-path }}/requirements.txt

    # The dnf module cannot be installed by pip, so it's only possible to use
    # it when using the system pyhton interpreter.
    - name: Install DNF module
      if: "${{ inputs.use-system-python == 'true' }}"
      shell: bash
      run: |
        if [ "${{ steps.os-check.outputs.is-fedora }}" = "true" ]; then
          sudo dnf install -y python3-dnf
        else
          sudo apt-get update
          sudo apt-get install python3-dnf
        fi
