# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

name: "Prepare Python"
description: "Sets up the python environment"
inputs:
  checkout-path:
    description: "Where this project was checked out"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'

    - name: "Install and upgrade pip"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: "Install python dependencies for project"
      shell: bash
      run: pip install -r ${{ inputs.checkout-path }}/requirements.txt

    - name: "Install dnf"
      run: pip install dnf
