# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

name: "Prepare Python"
description: "Sets up the python environment"
inputs:
  checkout-path:
    description: "Where this project was checked out"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    # It's not possible to install dnf via pip.  It fails with the error:
    # RuntimeError: Install aborted - please install python-dnf from distribution system.
    - name: "Install dnf"
      shell: bash
      run: |
        sudo apt-get install python3-dnf
        python3 -c 'import dnf'
        python3 -c 'import sys; print(sys.path)'
        which python3

    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'

    - name: "Install and upgrade pip"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: "Install python dependencies for project"
      shell: bash
      run: pip install -r ${{ inputs.checkout-path }}/requirements.txt

    - name: "Test dnf"
      shell: bash
      run: |
        python3 -c 'import sys; print(sys.path)'
        which python3
        python3 -c 'import dnf'
