# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "daily"
    assignees:
      - "kwk"
    labels: ["infrastructure", "dependencies", "dependabot"]
    target-branch: "main"
    commit-message:
      prefix: "prod"
      prefix-development: "dev"
      include: "scope"

updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    # Specify labels for pip pull requests
    labels:
      - "pip"
      - "python"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    labels:
      - "github-actions"
    multi-ecosystem-group: "infrastructure"
