mutation minimizeComment($id: ID!, $classifier: ReportedContentClassifiers! = OUTDATED) {
  minimizeComment(input: {subjectId: $id, classifier: $classifier}) {
    clientMutationId
    minimizedComment {
      isMinimized
      minimizedReason
      viewerCanMinimize
    }
  }
}
