# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

name: "Prepare Python"
description: "Sets up the python environment"
inputs:
  checkout-path:
    description: "Where this project was checked out"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: "Check for cached dependencies"
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: "Install and upgrade pip"
      run: python -m pip install --upgrade pip

    - name: "Install python dependencies for project"
      run: pip install -r ${{ inputs.checkout-path }}/requirements.txt
