name: build-and-upload-srpm

on:
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch: {}

jobs:

  build-and-upload-srpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-and-upload-srpm
        with:
          project-name: compiler-rt
      - run: |
         pwd
         ls -lha