name: "Check python code coverage"

on: [push, pull_request]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-python
        with:
          use-system-python: true
      - name: Run pytest with coverage
        shell: bash -e {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make ci-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          format: python
          file: .coverage
