name: "Check today's snapshot"

on:
  schedule:
    # At every 60th minute.
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron: "*/60 * * * *"

  workflow_dispatch: {}

permissions:
  # We need this in order to create or update snapshot issues
  issues: write

jobs:
  check-todays-snapshot:
    strategy:
      fail-fast: false
      matrix:
        name: [standalone, big-merge]
        include:
          - name: standalone
            maintainer_handle: "tuliom"
            copr_ownername: "@fedora-llvm-team"
            copr_project_tpl: "llvm-snapshots-incubator-YYYYMMDD"
            copr_monitor_tpl: "https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots-incubator-YYYYMMDD/monitor/"
            packages: "llvm-snapshot-builder python-lit llvm clang lld compiler-rt libomp"
          - name: big-merge
            maintainer_handle: "kwk"
            copr_ownername: "@fedora-llvm-team"
            copr_project_tpl: "llvm-snapshots-big-merge-YYYYMMDD"
            copr_monitor_tpl: "https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots-big-merge-YYYYMMDD/monitor/"
            chroot_pattern: '^(fedora-(rawhide|[0-9]+)|rhel-9-)'
            packages: "llvm"
          # - name: bootstrap
          #   maintainer_handle: "kwk"
          #   copr_ownername: "@fedora-llvm-team"
          #   copr_project_tpl: "llvm-snapshots-bootstrap-YYYYMMDD"
          #   copr_monitor_tpl: "https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots-bootstrap-YYYYMMDD/monitor/"
          #   chroot_pattern: 'fedora-39-x86_64'
          #   packages: "llvm"

    runs-on: ubuntu-latest
    steps:
      - name: Setup Copr config file
        env:
          # You need to have those secrets in your repo.
          # See also: https://copr.fedorainfracloud.org/api/.
          COPR_CONFIG_FILE: ${{ secrets.COPR_CONFIG }}
        run: |
          mkdir -p ~/.config
          printf "$COPR_CONFIG_FILE" > ~/.config/copr

      - name: Install Copr CLI
        run: |
          sudo apt-get install -y lsb-release diffutils pcre2-utils jq

      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-python

      - name: "Check todays builds"
        shell: bash -e {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTING_FARM_API_TOKEN_PUBLIC_RANCH: ${{ secrets.TESTING_FARM_API_TOKEN_PUBLIC_RANCH }}
          TESTING_FARM_API_TOKEN_REDHAT_RANCH: ${{ secrets.TESTING_FARM_API_TOKEN_REDHAT_RANCH }}
        run: |
          extra_args=""

          if [[ ! -z "${{ matrix.chroot_pattern }}" ]]; then
            extra_args="${extra_args} --chroot-pattern ${{matrix.chroot_pattern}}"
          fi

          python3 snapshot_manager/main.py check ${extra_args}\
            --github-repo ${GITHUB_REPOSITORY} \
            --github-token-env GITHUB_TOKEN \
            --maintainer-handle ${{matrix.maintainer_handle}} \
            --packages ${{matrix.packages}} \
            --build-strategy ${{matrix.name}} \
            --copr-project-tpl ${{matrix.copr_project_tpl}} \
            --copr-monitor-tpl ${{matrix.copr_monitor_tpl}}
