name: Build on Copr

on:
  workflow_dispatch: {}

jobs:
  build_packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install copr
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Batch build on copr
      env:
        COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
        COPR_URL: ${{ secrets.COPR_URL }}
        COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
        COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
      run: |
        python build-on-copr.py
