name: "copr-manual"

on:
  workflow_dispatch:
    inputs:
      chroots:
        description: 'chroots to build in separated by spaces (or "all" to select a default)'
        required: false
        default: all
      yyyymmdd:
        description: 'build snapshots for this year month day combination'
        required: false
        default: '20210908'
      packagenames:
        description: 'package names to build separated by spaces (or all to build all)'
        required: false
        default: 'python-lit compat-llvm compat-clang llvm compiler-rt lld clang'
      ownername:
        description: 'owner (or group) name of the copr project to be created or checked for existence'
        required: false
        default: 'kkleine'
      projectname:
        description: 'project name of the copr project'
        required: false
        default: 'llvm-snapshots'
      timeout:
        description: 'timeout in seconds for each package to build'
        required: false
        default: '108000'
      wait_on_build_id:
        description: "build id to wait for (0 = don't wait)"
        required: false
        default: '0'
      wipe_project:
        description: "delete the project before creating it (this also cancels running builds)"
        required: false
        default: false

jobs:
  build_packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
        python -m pip install --upgrade pip
        pip install copr==1.112
    - name: wipe project
      if: github.event.inputs.wipe-project
      env:
        COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
        COPR_URL: ${{ secrets.COPR_URL }}
        COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
        COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
      run: |
        python fedora-copr/build.py \
          --ownername "${{ github.event.inputs.ownername }}" \
          --projectname "${{ github.event.inputs.projectname }}" \
          --delete-project True

    - name: Batch build on copr
      env:
        COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
        COPR_URL: ${{ secrets.COPR_URL }}
        COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
        COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
      run: |
        python fedora-copr/build.py \
          --chroots ${{ github.event.inputs.chroots }} \
          --yyyymmdd "${{ github.event.inputs.yyyymmdd }}" \
          --packagenames ${{ github.event.inputs.packagenames }} \
          --ownername "${{ github.event.inputs.ownername }}" \
          --projectname "${{ github.event.inputs.projectname }}" \
          --timeout "${{ github.event.inputs.timeout }}" \
          --wait-on-build-id "${{ github.event.inputs.wait_on_build_id }}"
