name: date-test

on:
  workflow_dispatch:
    inputs:
      foo:
        description: "foo"
        required: false
        default: 'False'

  schedule:
    # Everyday at 00:00am
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron:  '15 19 * * *'

jobs:

  run:
    name: output date
    if: ${{ github.event.inputs.foo == 'False' || github.event.inputs.foo == '' }}
    runs-on: ubuntu-latest
    steps:

      - name: output date
        run: |
          date
          