name: llvm-snapshot

# PURPOSE:
#
#   We want to provide LLVM snapshot packagers and distributors with *daily*
#   source tarballs that are easy to consume. Typically, packagers have to clone
#   the whole LLVM monorepo themselves and run the "git archive" command to
#   generate source tarballs for each LLVM component. Those tarballs are the
#   input to the packaging system (e.g. DEB, RPM, etc.). With this workflow we
#   can provide the daily source tarballs to the community similar to the source
#   tarballs of regular releases. Everything a packager needs to know is the
#   current date (YYYYMMDD) and go ahead and download the LLVM component of
#   choice, i.e.:
#
#   https://github.com/{owner}/llvm-daily-fedora-rpms/releases/download/source-snapshot/clang-tools-extra-20210417.src.tar.xz
#
#   Notice the absence of the LLVM version. To get it, a packager can download
#
#   https://github.com/{owner}/llvm-daily-fedora-rpms/releases/download/source-snapshot/llvm-release-20210417.src.tar.xz
#
#   To get the git revision standalone:
#
#   https://github.com/{owner}/llvm-daily-fedora-rpms/releases/download/source-snapshot/llvm-git-revision-20210417.src.tar.xz
#
#   The subtle benefit of this naming convention is that you don't need to know
#   the LLVM version before downloading the source tarball. I mean, how could
#   you know the LLVM version of a daily snapshot upfront? In fact, the source
#   tarball for "clang-tools-extra" contains no version information whatsoever
#   and yet it requires a special LLVM version which is why we provide the
#   "llvm-release-<YYYYMMDD>.txt" files.
#
# WHAT:
#
#   At 00:00 in the morning, this workflow creates source tarballs for the
#   latest stable commit of all LLVM components of the current "main" branch and
#   uploads them as assets to a pre-release called "source-snapshot". (A
#   pre-release won't show up on the github repositories front-page.) The assets
#   that are seven days or older will be deleted on each run. If the workflow
#   runs twice a day, the old assets of the day will also be deleted. If the
#   "source-snapshot" release doesn't exist, it will be created automatically.

on:
  # Uncomment to be able to trigger the workflow manually
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch:
    inputs:
      skip_tarball_generation:
        description: "Skip source tarball generation (default: False)"
        required: false
        default: 'False'
      skip_copr_build:
        description: "Skip Fedora Copr build (default: False)"
        required: false
        default: 'False'

  schedule:
    # Everyday at 00:00am
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron:  '30 19 * * *'

jobs:

  # In order to re-build source snapshots and upload them, we must first delete
  # the old ones from today; otherwise there would be a conflict. As a measure
  # of not storing old snapshots for too long we'll delete older ones here as
  # well.
  source-tarballs:
    name: create source snapshots
    if: ${{ github.event.inputs.skip_tarball_generation != 'True' }}
    runs-on: ubuntu-latest
    steps:

      - name: "install PyGithub"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install PyGithub copr==1.112
      
      - name: checkout this project
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          path: llvm-daily-fedora-rpms

      - name: checkout llvm/llvm-project
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          path: llvm-project

      - name: determine last stable commit of llvm/llvm-project
        id: stable-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sha=`llvm-daily-fedora-rpms/.github/workflows/get-good-commit.py --token ${{ secrets.GITHUB_TOKEN }} --project "llvm/llvm-project" --start-ref main --ensure-checks clang-x86_64-debian-fast llvm-clang-x86_64-expensive-checks-debian`
          echo -n "::set-output name=sha::$sha"
      
      - name: fetch stable revision to archive
        run: git -C llvm-project fetch --depth=1 --no-tags origin ${{ steps.stable-commit.outputs.sha }}

      - name: delete assets older than a week and from today
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          llvm-daily-fedora-rpms/.github/workflows/delete-assets.py \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --project ${{ github.repository }} \
            --release-name source-snapshot \
            --delete-older 7 \
            --delete-today True

      - name: create source-snapshot tarballs
        run: |
          llvm-project/llvm/utils/release/export.sh \
            --git-ref ${{ steps.stable-commit.outputs.sha }} \
            --template '${PROJECT}-${YYYYMMDD}.src.tar.xz'
      
      - name: upload source-snapshots and version files to ${{ github.repository }} pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          llvm-daily-fedora-rpms/.github/workflows/upload-source-snapshots.py \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --project ${{ github.repository }} \
            --release-name source-snapshot \
            --yyyymmdd "$(date +%Y%m%d)"
    
  copr-build:
    name: Fedora Copr
    if: ${{ always() && (github.event.inputs.skip_copr_build != 'True' }}
    needs: source-tarballs
    runs-on: ubuntu-latest  
    steps:
      - name: install python copr library
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install copr==1.112

      - uses: actions/checkout@v2
        
      - name: copr build
        env:
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_URL: ${{ secrets.COPR_URL }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python fedora-copr/build.py \
            --chroots fedora-34-aarch64 fedora-35-aarch64 fedora-rawhide-aarch64 fedora-34-x86_64 fedora-35-x86_64 fedora-rawhide-x86_64 \
            --yyyymmdd "$(date +%Y%m%d)" \
            --ownername "@fedora-llvm-team" \
            --projectname "llvm-snapshots" \
            --timeout "108000" \
            --with-compat False
