name: "Start performance comparison"

on:
  schedule:
    # Everyday at 00:45am
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron: "45 0 * * *"

  workflow_dispatch:

permissions:
  # We need this in order to create or update issues
  issues: write

jobs:
  start-performance-comparison:
    if: github.repository_owner == 'fedora-llvm-team'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-python
      - name: "start-performance-comparison"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTING_FARM_API_TOKEN_PUBLIC_RANCH: ${{ secrets.TESTING_FARM_API_TOKEN_PUBLIC_RANCH }}
          TESTING_FARM_API_TOKEN_REDHAT_RANCH: ${{ secrets.TESTING_FARM_API_TOKEN_REDHAT_RANCH }}
        run: |
          today=$(date +%Y%m%d)
          yesterday=$(date -d "${today} -1 day" +%Y%m%d)

          python3 ./snapshot_manager/main.py \
            --github-repo "${GITHUB_REPOSITORY}" \
            run-perf-comparison \
            --strategy-a pgo \
            --strategy-b big-merge \
            --yyyymmdd "$yesterday"
