name: "Test iterating over chroots from matrix"

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'build strategy'
        required: true
        type: choice
        default: all
        options:
        - all
        - big-merge
        - pgo

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-python
    - name: Setup Copr config file
      env:
        # You need to have those secrets in your repo.
        # See also: https://copr.fedorainfracloud.org/api/.
        COPR_CONFIG: ${{ secrets.COPR_CONFIG }}
      run: |
        mkdir -p ~/.config
        echo "$COPR_CONFIG" > ~/.config/copr
    - name: generate-matrix
      id: set-matrix
      run: |
        # shellcheck disable=SC2086
        matrix="$(python3 snapshot_manager/main.py github-matrix --strategy ${{ inputs.strategy }})"
        echo "$matrix"
        echo "myoutput=$matrix" >> "$GITHUB_OUTPUT"

  build-on-copr:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.mymatrix)}}
    runs-on: ubuntu-latest
    container: fedora:41
    steps:
      - uses: actions/checkout@v4

      - name: "Print matrix"
        shell: bash -e {0}
        run: |
          echo "name = ${{matrix.name}}"
          echo "copr_target_project = ${{matrix.copr_target_project}}"
          echo "clone_url = ${{matrix.clone_url}}"
          echo "clone_ref = ${{matrix.clone_ref}}"
          echo "maintainer_handle = ${{matrix.maintainer_handle}}"
          echo "copr_ownername = ${{matrix.copr_ownername}}"
          echo "copr_project_tpl = ${{matrix.copr_project_tpl}}"
          echo "copr_monitor_tpl = ${{matrix.copr_monitor_tpl}}"
          echo "chroot_pattern = ${{matrix.chroot_pattern}}"
          echo "chroots = ${{matrix.chroots}}"

          for chroot in ${{matrix.chroots}}; do
            echo "chroot=$chroot"
          done
