name: "Update diagrams"

on:
  schedule:
    # At 23:00
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron: "0 23 * * *"

  workflow_dispatch:
    inputs:
      get_stats:
        description: 'Get stats'
        default: true
        required: false
        type: boolean
      create_diagrams:
          description: 'Create diagrams'
          default: true
          required: false
          type: boolean

permissions:
  # This should allow the workflow to create github pages
  pages: write
  # This should allow the workflow to create a new commit in the gh-branch
  contents: write

jobs:
  update-build-time-diagrams:
    if: github.repository_owner == 'fedora-llvm-team'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Copr config file
        env:
          # You need to have those secrets in your repo.
          # See also: https://copr.fedorainfracloud.org/api/.
          COPR_CONFIG_FILE: ${{ secrets.COPR_CONFIG }}
        run: |
          mkdir -p ~/.config
          echo "$COPR_CONFIG_FILE" > ~/.config/copr

      - uses: actions/checkout@v4
        with:
          path: main

      - uses: ./main/.github/actions/prepare-python
        with:
          checkout-path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Setup git config
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "<>"

      - name: "Update stats and re-generate diagrams"
        shell: bash -e {0}
        env:
          get_stats: ${{ github.event_name == 'schedule' && true || github.event.inputs.get_stats }}
          create_diagrams: ${{ github.event_name == 'schedule' && true || github.event.inputs.create_diagrams }}
        run: |
          today=$(date +%Y%m%d)
          yesterday=$(date -d "${today} -1 day" +%Y%m%d)

          if ${{ env.get_stats }}; then
            main/scripts/get-build-stats.py --copr-projectname "llvm-snapshots-big-merge-${today}" | tee -a gh-pages/build-stats-big-merge.csv
            main/scripts/get-build-stats.py --copr-projectname "llvm-snapshots-pgo-${today}" | tee -a gh-pages/build-stats-pgo.csv
            python3 ./main/snapshot_manager/main.py collect-perf-results \
              --strategy-a pgo \
              --strategy-b big-merge \
              --csv-file-in gh-pages/perf-results.csv \
              --csv-file-out gh-pages/perf-results.csv \
              --yyyymmdd "${yesterday}"
            git -C gh-pages add build-stats-big-merge.csv build-stats-pgo.csv perf-results.csv
          fi
          if ${{ env.create_diagrams }}; then
            main/scripts/create-build-time-diagrams.py --datafile-big-merge gh-pages/build-stats-big-merge.csv --datafile-pgo gh-pages/build-stats-pgo.csv
            mv index.html gh-pages/index.html
            mv fig-*.html gh-pages/
            python3 ./main/snapshot_manager/main.py perf-diagrams --datafile gh-pages/perf-results.csv
            mkdir -p gh-pages/perf-results
            mv index.html gh-pages/perf-results/index.html
            mv fig-*.html gh-pages/perf-results/
            git -C gh-pages add index.html fig-*.html perf-results/index.html perf-results/fig-*.html
          fi
          # shellcheck disable=SC2078
          if [[ ${{ env.get_stats }} || ${{ env.create_diagrams }} ]]; then
            cd gh-pages
            git commit -m "Automatically update build and performance stats"
            git push origin HEAD:gh-pages
          fi
