FROM fedora:41
LABEL description="Test compilers with llvm-test-suite"

USER root
WORKDIR /root

# Install deps to run test-suite
RUN dnf install -y \
        clang \
        cmake \
        coreutils \
        envsubst \
        fedora-packager \
        git \
        jq \
        jq \
        ninja-build \
        perf
        python3-lit \
        python3-pandas \
        python3-pip \
        python3-scipy
        python3-setuptools \
        python3-virtualenv \
        tcl \
        tcl-devel \
        tcl-tclreadline \
        tcl-tclxml \
        tcl-tclxml-devel \
        tcl-thread-devel \
        tcl-zlib \
        which \

# Clone test suite (in correct version for installed clang version)
# See https://llvm.org/docs/TestSuiteGuide.html
# RUN export VERSION=`clang --version | grep -ioP 'clang version\s\K[0-9\.]+'` \
#     && git clone --depth=1 --branch llvmorg-${VERSION} https://github.com/llvm/llvm-test-suite.git test-suite
RUN git clone --depth=1 https://github.com/llvm/llvm-test-suite.git test-suite

RUN dnf install -y 'dnf-command(copr)'

COPY entrypoint.sh /root/entrypoint.sh
USER root
ENTRYPOINT [ "/root/entrypoint.sh" ]
